#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:		pos
# Required-Start:	$local_fs $network 
# Required-Stop:	$local_fs $network 
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Covetel POS
### END INIT INFO

case "$1" in
    start)
        /opt/covetel/pos/bin/pos.pl start
        ;;
    stop)
        /opt/covetel/pos/bin/pos.pl stop
        ;;
    status)
        /opt/covetel/pos/bin/pos.pl status
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

exit 0

